'use server';
/**
 * @fileOverview A simple text generation flow using Genkit with dynamic config.
 * 
 * - generateSimpleText - A function that calls the text generation flow.
 * - businessId - Optional parameter to fetch the AI configuration (API Key/Provider) from Firestore.
 */

import { ai } from '@/ai/genkit';
import { z } from 'zod';
import { getAIConfig } from './chat-flow';

const SimpleTextInputSchema = z.object({
  prompt: z.string().describe("The text prompt to send to the AI model."),
  businessId: z.string().optional().describe("Optional business ID to fetch specific AI config.")
});
export type SimpleTextInput = z.infer<typeof SimpleTextInputSchema>;

const SimpleTextOutputSchema = z.string().describe("The text generated by the AI model.");
export type SimpleTextOutput = z.infer<typeof SimpleTextOutputSchema>;

/**
 * Generates simple text using the AI model configured for the platform or a specific business.
 * @param prompt The text prompt to send to the model.
 * @param businessId Optional business ID to use business-specific AI settings.
 */
export async function generateSimpleText(prompt: string, businessId?: string): Promise<string> {
  return simpleTextFlow({ prompt, businessId });
}

const simpleTextFlow = ai.defineFlow(
  {
    name: 'simpleTextFlow',
    inputSchema: SimpleTextInputSchema,
    outputSchema: z.string(),
  },
  async (input) => {
    // Obtener la configuración (API Key, Proveedor, Modelo) de forma dinámica
    const aiConfig = await getAIConfig(input.businessId);

    // Validación de seguridad: si se pasó un businessId y no hay llave, informar al usuario
    if (input.businessId && !aiConfig.apiKey) {
        throw new Error("Configuración de IA no encontrada para este negocio. Por favor, contacta al administrador.");
    }

    // CASO 1: Google AI (Gemini)
    if (aiConfig.provider === 'googleai') {
      const llmResponse = await ai.generate({
        model: `googleai/${aiConfig.model}`,
        prompt: input.prompt,
        config: {
          temperature: 0.7,
          apiKey: aiConfig.apiKey, // Inyección dinámica de la llave desde Firestore
        },
      });

      return llmResponse.text ?? "No se pudo generar una respuesta.";
    }

    // CASO 2: Proveedores compatibles con OpenAI (OpenAI, Groq, etc.)
    try {
      const endpoint = aiConfig.provider === 'groq'
        ? 'https://api.groq.com/openai/v1/chat/completions'
        : 'https://api.openai.com/v1/chat/completions';

      const response = await fetch(endpoint, {
        method: 'POST',
        headers: { 
          'Authorization': `Bearer ${aiConfig.apiKey}`, 
          'Content-Type': 'application/json' 
        },
        body: JSON.stringify({
          messages: [
            { role: 'user', content: input.prompt }
          ],
          model: aiConfig.model,
          temperature: 0.7,
        }),
      });

      if (!response.ok) {
          const errorData = await response.json();
          throw new Error(errorData.error?.message || "Error en el proveedor de IA.");
      }

      const data = await response.json();
      return data.choices?.[0]?.message?.content || 'No se pudo generar una respuesta.';

    } catch (e: any) {
      console.error("[simpleTextFlow] Error:", e.message);
      throw new Error(`Fallo en la comunicación con la IA: ${e.message}`);
    }
  }
);
