'use server';
/**
 * @fileOverview A simple text generation flow using Genkit.
 * This demonstrates how to use the existing Genkit setup to call Google's AI models.
 *
 * - generateSimpleText - A function that calls the text generation flow.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const SimpleTextInputSchema = z.string().describe("The text prompt to send to the AI model.");
export type SimpleTextInput = z.infer<typeof SimpleTextInputSchema>;

const SimpleTextOutputSchema = z.string().describe("The text generated by the AI model.");
export type SimpleTextOutput = z.infer<typeof SimpleTextOutputSchema>;

export async function generateSimpleText(prompt: SimpleTextInput): Promise<SimpleTextOutput> {
  return simpleTextFlow(prompt);
}

const simpleTextFlow = ai.defineFlow(
  {
    name: 'simpleTextFlow',
    inputSchema: SimpleTextInputSchema,
    outputSchema: SimpleTextOutputSchema,
  },
  async (prompt) => {
    // This uses the configured Google AI plugin to call a Gemini model,
    // which is part of the Vertex AI platform.
    const llmResponse = await ai.generate({
      model: 'googleai/gemini-1.5-flash', // A powerful and fast model from Vertex AI
      prompt: prompt,
      config: {
        temperature: 0.7,
      },
    });

    return llmResponse.text ?? "No se pudo generar una respuesta.";
  }
);
