'use server';
/**
 * @fileOverview A simple text generation flow using Genkit with dynamic config.
 * 
 * - generateSimpleText - A function that calls the text generation flow.
 * - businessId - Optional parameter to fetch the AI configuration (API Key/Provider) from Firestore.
 */

import { ai } from '@/ai/genkit';
import { z } from 'zod';
import { getAIConfig } from './chat-flow';

const SimpleTextInputSchema = z.object({
  prompt: z.string().describe("The text prompt to send to the AI model."),
  businessId: z.string().optional().describe("Optional business ID to fetch specific AI config.")
});
export type SimpleTextInput = z.infer<typeof SimpleTextInputSchema>;

const SimpleTextOutputSchema = z.string().describe("The text generated by the AI model.");
export type SimpleTextOutput = z.infer<typeof SimpleTextOutputSchema>;

/**
 * Generates simple text using the AI model configured for the platform or a specific business.
 * @param prompt The text prompt to send to the model.
 * @param businessId Optional business ID to use business-specific AI settings.
 */
export async function generateSimpleText(prompt: string, businessId?: string): Promise<string> {
  return simpleTextFlow({ prompt, businessId });
}

const simpleTextFlow = ai.defineFlow(
  {
    name: 'simpleTextFlow',
    inputSchema: SimpleTextInputSchema,
    outputSchema: z.string(),
  },
  async (input) => {
    // Obtener la configuración (API Key, Proveedor, Modelo) de forma dinámica.
    // La función getAIConfig ya consulta el documento global de integraciones del Super Admin.
    const aiConfig = await getAIConfig(input.businessId);

    // Validación de seguridad global: si no hay ninguna llave configurada en la plataforma.
    if (!aiConfig.apiKey) {
        return "⚠️ [Error de Configuración]: El administrador de la plataforma no ha configurado las llaves de IA en el panel de Super Admin.";
    }

    // CASO 1: Google AI (Gemini)
    if (aiConfig.provider === 'googleai') {
      const llmResponse = await ai.generate({
        model: `googleai/${aiConfig.model}`,
        prompt: input.prompt,
        config: {
          temperature: 0.7,
          apiKey: aiConfig.apiKey, // Inyección dinámica de la llave desde Firestore (Motor Global)
        },
      });

      return llmResponse.text ?? "No se pudo generar una respuesta.";
    }

    // CASO 2: Proveedores compatibles con OpenAI (OpenAI, Groq, DeepSeek, etc.)
    try {
      let endpoint = 'https://api.openai.com/v1/chat/completions';
      if (aiConfig.provider === 'groq') {
        endpoint = 'https://api.groq.com/openai/v1/chat/completions';
      } else if (aiConfig.provider === 'deepseek') {
        endpoint = 'https://api.deepseek.com/v1/chat/completions';
      }

      const response = await fetch(endpoint, {
        method: 'POST',
        headers: { 
          'Authorization': `Bearer ${aiConfig.apiKey}`, 
          'Content-Type': 'application/json' 
        },
        body: JSON.stringify({
          messages: [
            { role: 'user', content: input.prompt }
          ],
          model: aiConfig.model,
          temperature: 0.7,
        }),
      });

      if (!response.ok) {
          const errorData = await response.json();
          throw new Error(errorData.error?.message || "Error en el proveedor de IA.");
      }

      const data = await response.json();
      return data.choices?.[0]?.message?.content || 'No se pudo generar una respuesta.';

    } catch (e: any) {
      console.error("[simpleTextFlow] Error:", e.message);
      return `❌ [Error de Comunicación]: Fallo al contactar con el proveedor de IA (${aiConfig.provider}).`;
    }
  }
);