// ... imports existentes ...

const DEFAULT_MODULES: { name: string; description: string; limit: number; idOverride?: string }[] = [
    // ... items existentes ...
    { name: 'Directorio de Negocios', description: 'Módulo para listar el negocio en el directorio público de la plataforma.', limit: -1, idOverride: 'business-directory' },
    { name: 'Chatbot Menú Público', description: 'Asistente IA que responde dudas en el catálogo público basándose en el menú y promos.', limit: -1, idOverride: 'public-menu-chatbot' },
];

// ... resto del archivo ...
